import AppKit
import CryptoKit
import Foundation

public struct Clip: Identifiable, Sendable, Equatable, Codable {
    public enum Kind: String, Sendable, Codable {
        case string, rtf, rtfd, pdf, tiff, url, filenames
    }

    public var id: Int64 = 0
    public let kind: Kind
    public let hash: String
    public let preview: String
    public let text: String?
    public let blob: Data?
    public var sourceBundle: String?
    public let createdAt: Date
    public var lastUsedAt: Date
    public var pinned: Bool = false
}

extension Notification.Name {
    static let clipsDidChange = Notification.Name("dev.clipmouse.clipsDidChange")
    static let secretBlocked = Notification.Name("dev.clipmouse.secretBlocked")
}

/// Чтение буфера -> Clip и Clip -> буфер.
/// Порядок типов при чтении (§9 Фаза 1): .fileURL → .URL → .rtfd → .rtf → .pdf → .tiff → .string.
enum ClipboardIO {

    static let concealedMarkers: [NSPasteboard.PasteboardType] = [
        .init(rawValue: "org.nspasteboard.ConcealedType"),
        .init(rawValue: "org.nspasteboard.TransientType"),
        .init(rawValue: "org.nspasteboard.AutoGeneratedType"),
    ]

    static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Превью: схлопнутые \n \t и повторные пробелы, потолок 200 символов (§4).
    static func normalizedPreview(_ s: String) -> String {
        var collapsed = String()
        var pendingSpace = false
        for ch in s {
            if ch == "\n" || ch == "\r" || ch == "\t" || ch == " " {
                pendingSpace = !collapsed.isEmpty
            } else {
                if pendingSpace { collapsed.append(" "); pendingSpace = false }
                collapsed.append(ch)
            }
        }
        if collapsed.count > 200 { collapsed = String(collapsed.prefix(200)) + "…" }
        return collapsed
    }

    static func byteSizeLabel(_ byteCount: Int) -> String {
        let f = ByteCountFormatter()
        f.countStyle = .file
        return f.string(fromByteCount: Int64(byteCount))
    }

    // MARK: - Чтение

    /// nil — буфер пуст, помечен маркером приватности или превышает лимиты.
    static func read(from pb: NSPasteboard, prefs: Prefs) -> Clip? {
        guard let types = pb.types, !types.isEmpty else { return nil }
        if types.contains(where: { concealedMarkers.contains($0) }) { return nil }

        let now = Date()

        if types.contains(.fileURL),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            if urls.count == 1 {
                let u = urls[0]
                let abs = u.absoluteString
                guard abs.utf8.count <= prefs.historyMaxClipTextBytes else { return nil }
                return Clip(kind: .url, hash: sha256Hex(Data(abs.utf8)),
                            preview: normalizedPreview((abs as NSString).lastPathComponent.isEmpty ? abs : (abs as NSString).lastPathComponent),
                            text: abs, blob: nil, sourceBundle: nil, createdAt: now, lastUsedAt: now)
            }
            let paths = urls.map(\.path)
            if let json = try? JSONEncoder().encode(paths), json.count <= prefs.historyMaxClipTextBytes {
                let names = paths.map { ($0 as NSString).lastPathComponent }
                return Clip(kind: .filenames, hash: sha256Hex(json),
                            preview: normalizedPreview(names.joined(separator: ", ")),
                            text: String(data: json, encoding: .utf8), blob: nil,
                            sourceBundle: nil, createdAt: now, lastUsedAt: now)
            }
            return nil
        }

        if types.contains(.URL),
           let s = pb.string(forType: .URL), !s.isEmpty,
           s.utf8.count <= prefs.historyMaxClipTextBytes {
            return Clip(kind: .url, hash: sha256Hex(Data(s.utf8)),
                        preview: normalizedPreview(s), text: s, blob: nil,
                        sourceBundle: nil, createdAt: now, lastUsedAt: now)
        }

        for (type, kind) in [(NSPasteboard.PasteboardType.rtfd, Clip.Kind.rtfd),
                             (.rtf, .rtf),
                             (.pdf, .pdf),
                             (.tiff, .tiff)] {
            if types.contains(type),
               let data = pb.data(forType: type), !data.isEmpty,
               data.count <= prefs.historyMaxBlobBytes {
                let text = pb.string(forType: .string)
                return Clip(kind: kind, hash: sha256Hex(data),
                            preview: binaryPreview(kind: kind, blob: data),
                            text: (text?.utf8.count ?? 0) <= prefs.historyMaxClipTextBytes ? text : nil,
                            blob: data, sourceBundle: nil, createdAt: now, lastUsedAt: now)
            }
        }

        if types.contains(.string),
           let s = pb.string(forType: .string), !s.isEmpty,
           s.utf8.count <= prefs.historyMaxClipTextBytes {
            return Clip(kind: .string, hash: sha256Hex(Data(s.utf8)),
                        preview: normalizedPreview(s), text: s, blob: nil,
                        sourceBundle: nil, createdAt: now, lastUsedAt: now)
        }

        return nil
    }

    private static func binaryPreview(kind: Clip.Kind, blob: Data) -> String {
        let size = byteSizeLabel(blob.count)
        if kind == .tiff, let rep = NSBitmapImageRep(data: blob) {
	            return String(format: String(localized: "image.preview"),
	                            rep.pixelsWide, rep.pixelsHigh, size)
        }
        return "\(kind.rawValue.uppercased()) · \(size)"
    }

    // MARK: - Запись

    /// Запись голой строки (сниппеты после разворота плейсхолдеров).
    /// Зовётся только вместе с monitor.ignoreNextChange().
    static func writeString(_ s: String, to pb: NSPasteboard = .general) {
        pb.clearContents()
        pb.setString(s, forType: .string)
    }

    /// Выбор пункта меню кладёт клип в буфер (авто-⌘V нет: inputPasteCommand = 0).
    /// Зовётся только вместе с monitor.ignoreNextChange(), иначе монитор
    /// поймает собственную запись.
    static func write(_ clip: Clip, to pb: NSPasteboard = .general) {
        pb.clearContents()
        switch clip.kind {
        case .string:
            pb.setString(clip.text ?? "", forType: .string)
        case .url:
            if let text = clip.text, let u = URL(string: text) {
                pb.writeObjects([u as NSURL])
            } else if let text = clip.text {
                pb.setString(text, forType: .string)
            }
        case .filenames:
            let paths = (clip.text.flatMap { try? JSONDecoder().decode([String].self, from: Data($0.utf8)) }) ?? []
            let urls = paths.compactMap { URL(fileURLWithPath: $0) as NSURL? }
            if !urls.isEmpty { pb.writeObjects(urls) }
        case .rtf, .rtfd, .pdf, .tiff:
            if let blob = clip.blob {
                pb.setData(blob, forType: NSPasteboard.PasteboardType(rawValue: kindType(clip.kind)))
            }
        }
    }

    static func kindType(_ kind: Clip.Kind) -> String {
        switch kind {
        case .string: return NSPasteboard.PasteboardType.string.rawValue
        case .rtf: return NSPasteboard.PasteboardType.rtf.rawValue
        case .rtfd: return NSPasteboard.PasteboardType.rtfd.rawValue
        case .pdf: return NSPasteboard.PasteboardType.pdf.rawValue
        case .tiff: return NSPasteboard.PasteboardType.tiff.rawValue
        case .url: return NSPasteboard.PasteboardType.URL.rawValue
        case .filenames: return NSPasteboard.PasteboardType.fileURL.rawValue
        }
    }
}
